"""Compute the ratio constants c_min^h and c_max^h underlying the
Wuzi ratio-bound theorem (Theorem B.1 in docs/wuzi_bounds_strategy.md):

  c_min^h * I_h(G) <= W(G; alpha, beta, gamma) <= c_max^h * I_h(G)

where

  c_min^h = min   psi(i, j; alpha, beta, gamma) / h(i, j)
  c_max^h = max   psi(i, j; alpha, beta, gamma) / h(i, j)
            (i, j) admissible

over the 10 admissible degree pairs on Delta <= 4 graphs.

The script is rigorous: it brute-forces the finite-set extremum
that the theorem prescribes; no theorem statement is invented.

Outputs:
  results/wuzi_bounds_ratio_tables.csv
  results/wuzi_bounds_ratio_tables.md
"""
from __future__ import annotations
import os
import math
from typing import Callable

import pandas as pd

THIS_DIR = os.path.abspath(os.path.dirname(__file__))
PROJECT = os.path.abspath(os.path.join(THIS_DIR, ".."))

DELTA_MAX = 4

PARAMETER_TRIPLES: list[tuple[float, float, float]] = [
    (1.0, 0.0, 0.0),       # M_2
    (-0.5, 0.0, 0.0),      # Randic R
    (0.0, -0.5, 0.0),      # Sum-connectivity SCI
    (0.0, -1.0, 0.0),      # Half-harmonic H/2
    (0.0, 0.0, 1.0),       # gamma sweep
    (0.0, 0.0, 2.0),
    (1.0, 1.0, 1.0),       # mixed positive
    (-1.0, -1.0, 1.0),     # FreeSolv passing parameter triple
]


def psi(i: int, j: int, alpha: float, beta: float, gamma: float) -> float:
    """Wuzi edge-contribution function on the unordered pair {i, j}."""
    return (
        (i * j) ** alpha
        * (i + j) ** beta
        * math.exp(gamma * abs(i - j) / (i + j))
    )


def admissible_pairs(delta_max: int) -> list[tuple[int, int]]:
    """Unordered admissible degree pairs (i, j) with 1 <= i <= j <= delta_max."""
    return [(i, j) for i in range(1, delta_max + 1) for j in range(i, delta_max + 1)]


# Edge contributions h(i, j) of seven classical BID indices.
# Each is a closed-form function on unordered positive integer pairs.
CLASSICAL_INDICES: dict[str, Callable[[int, int], float]] = {
    "M1":  lambda i, j: i + j,
    "M2":  lambda i, j: i * j,
    "R":   lambda i, j: 1.0 / math.sqrt(i * j),
    "SO":  lambda i, j: math.sqrt(i * i + j * j),
    "GA":  lambda i, j: 2.0 * math.sqrt(i * j) / (i + j),
    "H":   lambda i, j: 2.0 / (i + j),
    "ABC": lambda i, j: math.sqrt(max(0.0, (i + j - 2.0) / (i * j))),
}

# Indices for which h(i, j) > 0 on every admissible pair (1..Delta_max).
# ABC vanishes at (1, 1) so the ratio bound on ABC is restricted to graphs
# without a (1, 1) edge (equivalently any connected graph with >= 3 vertices).
ABC_PROBLEM_PAIRS = [(1, 1)]


def ratio_constants(
    alpha: float,
    beta: float,
    gamma: float,
    h_name: str,
    h_fn: Callable[[int, int], float],
    pairs: list[tuple[int, int]],
) -> tuple[float, float, tuple[int, int], tuple[int, int], int]:
    """Return (c_min, c_max, argmin_pair, argmax_pair, n_pairs_used)."""
    skipped = ABC_PROBLEM_PAIRS if h_name == "ABC" else []
    used = [p for p in pairs if p not in skipped]
    if not used:
        return float("nan"), float("nan"), (-1, -1), (-1, -1), 0
    best_min = math.inf
    best_max = -math.inf
    argmin: tuple[int, int] = (-1, -1)
    argmax: tuple[int, int] = (-1, -1)
    for (i, j) in used:
        h_ij = h_fn(i, j)
        if h_ij <= 0:
            continue
        ratio = psi(i, j, alpha, beta, gamma) / h_ij
        if ratio < best_min:
            best_min = ratio
            argmin = (i, j)
        if ratio > best_max:
            best_max = ratio
            argmax = (i, j)
    return best_min, best_max, argmin, argmax, len(used)


def main() -> None:
    pairs = admissible_pairs(DELTA_MAX)
    print(f"Admissible degree pairs on Delta <= {DELTA_MAX}: {len(pairs)} pairs")
    print(f"  -> {pairs}")
    print()

    rows = []
    for (alpha, beta, gamma) in PARAMETER_TRIPLES:
        for h_name, h_fn in CLASSICAL_INDICES.items():
            c_min, c_max, argmin, argmax, n_used = ratio_constants(
                alpha, beta, gamma, h_name, h_fn, pairs
            )
            rows.append({
                "alpha": alpha,
                "beta": beta,
                "gamma": gamma,
                "classical_index": h_name,
                "c_min": c_min,
                "c_max": c_max,
                "argmin_pair": f"({argmin[0]},{argmin[1]})",
                "argmax_pair": f"({argmax[0]},{argmax[1]})",
                "n_pairs_used": n_used,
            })

    df = pd.DataFrame(rows)
    out_csv = os.path.join(PROJECT, "results", "wuzi_bounds_ratio_tables.csv")
    df.to_csv(out_csv, index=False)

    md_lines: list[str] = []
    md_lines.append("# Ratio constants for the Wuzi ratio-bound theorem\n")
    md_lines.append("Generated by `scripts/09_wuzi_bounds_tables.py`.\n")
    md_lines.append(
        "For each parameter triple (alpha, beta, gamma) and each classical "
        "BID index $I_h$ with edge contribution $h(i, j)$, this table gives\n\n"
        "$$c_{\\min}^{h} = \\min_{(i,j)}\\, \\psi(i,j;\\alpha,\\beta,\\gamma) / h(i,j),"
        "\\quad c_{\\max}^{h} = \\max_{(i,j)}\\, \\psi/h,$$\n\n"
        "over the 10 admissible degree pairs $(i, j)$ with $1 \\le i \\le j \\le 4$.\n"
        "The corresponding bound (Theorem B.1 of `docs/wuzi_bounds_strategy.md`) is\n\n"
        "$$c_{\\min}^{h}\\, I_h(G) \\;\\le\\; W(G; \\alpha, \\beta, \\gamma) \\;\\le\\; c_{\\max}^{h}\\, I_h(G).$$\n\n"
        "The ratio bound is rigorous whenever $h(i, j) > 0$ on every admissible pair "
        "appearing in $G$. ABC vanishes at the $(1, 1)$ pair; the ABC ratio bound is "
        "therefore restricted to graphs without a $(1, 1)$ edge (any connected graph "
        "of order at least 3).\n"
    )

    md_lines.append("## Per-parameter, per-index ratio constants\n")
    md_lines.append(
        "| alpha | beta | gamma | $I_h$ | $c_{\\min}^h$ | $c_{\\max}^h$ "
        "| argmin (i,j) | argmax (i,j) | pairs used |"
    )
    md_lines.append("|---:|---:|---:|---|---:|---:|---|---|---:|")
    for r in rows:
        md_lines.append(
            f"| {r['alpha']:g} | {r['beta']:g} | {r['gamma']:g} | {r['classical_index']} | "
            f"{r['c_min']:.4f} | {r['c_max']:.4f} | {r['argmin_pair']} | "
            f"{r['argmax_pair']} | {r['n_pairs_used']} |"
        )

    md_lines.append("\n## Sanity check at exact reductions\n")
    md_lines.append(
        "When the Wuzi parameter triple coincides with a classical-index "
        "reduction, both $c_{\\min}^h$ and $c_{\\max}^h$ for that index should "
        "collapse to a constant (the Wuzi-classical identity is exact, not an "
        "inequality). Check the following rows in the table above:\n\n"
        "- $(\\alpha, \\beta, \\gamma) = (1, 0, 0)$ against $M_2$: should give "
        "$c_{\\min}^{M_2} = c_{\\max}^{M_2} = 1$.\n"
        "- $(\\alpha, \\beta, \\gamma) = (-1/2, 0, 0)$ against $R$: should give "
        "$c_{\\min}^{R} = c_{\\max}^{R} = 1$.\n"
        "- $(\\alpha, \\beta, \\gamma) = (0, -1, 0)$ against $H$: should give "
        "$c_{\\min}^{H} = c_{\\max}^{H} = 1/2$ (since $H = 2\\,W(\\cdot; 0, -1, 0)$).\n"
    )
    md_lines.append(
        "If the table values disagree, there is a bug in `psi` or in the classical-index "
        "edge contribution `h(i, j)`.\n"
    )

    out_md = os.path.join(PROJECT, "results", "wuzi_bounds_ratio_tables.md")
    with open(out_md, "w") as f:
        f.write("\n".join(md_lines))

    print(df.to_string(index=False, float_format=lambda v: f"{v:.4f}"))
    print()
    print(f"Written {out_csv}")
    print(f"Written {out_md}")


if __name__ == "__main__":
    main()
