"""Computational extremal-graph search for the Wuzi index family on trees.

Enumerates all non-isomorphic trees of order 5 <= n <= 12 using
networkx.generators.nonisomorphic_trees(n), computes
W(T; alpha, beta, gamma) at each parameter triple, and records the
minimizer and maximizer over the tree class.

Then checks whether the observed minimizer matches the path P_n and
the observed maximizer matches the star S_n at each parameter
triple (Conjecture D.1 of docs/wuzi_bounds_strategy.md).

This is *conjecture-generating* evidence, not proof. The output
should help Advik / Arockiaraj sir target a formal extremal-graph
characterization.

Outputs:
  results/wuzi_extremal_trees.csv
  results/wuzi_extremal_trees.md

Unicyclic and bicyclic enumeration is documented as a TODO below;
networkx does not provide a built-in non-isomorphic-unicyclic
enumerator and a hand-rolled version is left for future work.
"""
from __future__ import annotations
import math
import os
import sys
import time
from typing import Iterable

import networkx as nx
import pandas as pd

THIS_DIR = os.path.abspath(os.path.dirname(__file__))
PROJECT = os.path.abspath(os.path.join(THIS_DIR, ".."))
sys.path.insert(0, PROJECT)

TREE_ORDERS = list(range(5, 13))   # 5..12 inclusive

PARAMETER_TRIPLES: list[tuple[float, float, float]] = [
    (1.0, 0.0, 0.0),       # M_2
    (-0.5, 0.0, 0.0),      # Randic R
    (0.0, -0.5, 0.0),      # Sum-connectivity
    (0.0, -1.0, 0.0),      # Half-harmonic
    (0.0, 0.0, 1.0),       # gamma>0
    (0.0, 0.0, 2.0),
    (1.0, 1.0, 1.0),
    (-1.0, -1.0, 1.0),
]


def wuzi(G: nx.Graph, alpha: float, beta: float, gamma: float) -> float:
    """Compute W(G; alpha, beta, gamma) directly from the definition."""
    total = 0.0
    for u, v in G.edges():
        du, dv = G.degree(u), G.degree(v)
        prod = du * dv
        sm = du + dv
        imb = abs(du - dv) / sm
        total += (prod ** alpha) * (sm ** beta) * math.exp(gamma * imb)
    return total


def canonical_label(G: nx.Graph) -> str:
    """Deterministic isomorphism-invariant label for a tree: the WL hash.

    We use the Weisfeiler-Lehman graph hash which is invariant under
    isomorphism on trees (and very likely so on the small graphs we
    enumerate; collisions on trees of order <= 12 are not expected).
    """
    return nx.weisfeiler_lehman_graph_hash(G)


def path_label(n: int) -> str:
    return canonical_label(nx.path_graph(n))


def star_label(n: int) -> str:
    return canonical_label(nx.star_graph(n - 1))   # star_graph(k) has k+1 vertices


def main() -> None:
    t0 = time.time()
    rows = []
    print("=" * 64)
    print("Wuzi extremal-graph search on trees of order 5..12")
    print("=" * 64)

    for n in TREE_ORDERS:
        trees = list(nx.generators.nonisomorphic_trees(n))
        n_trees = len(trees)
        path_lbl = path_label(n)
        star_lbl = star_label(n)
        print(f"\nn = {n}: {n_trees} non-isomorphic trees")
        for (alpha, beta, gamma) in PARAMETER_TRIPLES:
            best_min = math.inf
            best_max = -math.inf
            argmin_idx = -1
            argmax_idx = -1
            for idx, T in enumerate(trees):
                w = wuzi(T, alpha, beta, gamma)
                if w < best_min:
                    best_min = w
                    argmin_idx = idx
                if w > best_max:
                    best_max = w
                    argmax_idx = idx
            argmin_lbl = canonical_label(trees[argmin_idx])
            argmax_lbl = canonical_label(trees[argmax_idx])
            min_is_path = argmin_lbl == path_lbl
            max_is_star = argmax_lbl == star_lbl
            w_path = wuzi(nx.path_graph(n), alpha, beta, gamma)
            w_star = wuzi(nx.star_graph(n - 1), alpha, beta, gamma)
            rows.append({
                "n": n,
                "n_trees": n_trees,
                "alpha": alpha,
                "beta": beta,
                "gamma": gamma,
                "w_min": best_min,
                "w_max": best_max,
                "w_path": w_path,
                "w_star": w_star,
                "min_is_path": min_is_path,
                "max_is_star": max_is_star,
            })

    df = pd.DataFrame(rows)
    out_csv = os.path.join(PROJECT, "results", "wuzi_extremal_trees.csv")
    df.to_csv(out_csv, index=False)

    md_lines: list[str] = []
    md_lines.append("# Wuzi extremal-graph search on trees of order 5..12\n")
    md_lines.append(f"Generated by `scripts/10_wuzi_extremal_search.py`.\n")
    md_lines.append(
        "For each tree order $n \\in \\{5, \\ldots, 12\\}$ and each "
        "parameter triple $(\\alpha, \\beta, \\gamma)$, the table below "
        "reports the minimum and maximum of $W(T; \\alpha, \\beta, \\gamma)$ "
        "over all non-isomorphic trees $T$ of order $n$, together with "
        "the Wuzi value at the path $P_n$ and the star $S_n$.\n\n"
        "Columns `min_is_path` and `max_is_star` indicate whether the "
        "observed minimizer coincides (via Weisfeiler--Lehman hash) with "
        "$P_n$ and the observed maximizer with $S_n$ respectively. A "
        "consistent `True` across orders is empirical support for "
        "Conjecture D.1 of `docs/wuzi_bounds_strategy.md`; a `False` "
        "indicates the conjecture fails at that parameter triple and "
        "the actual extremal is a different tree.\n"
    )

    md_lines.append("## Detailed table\n")
    md_lines.append(
        "| $n$ | trees | $\\alpha$ | $\\beta$ | $\\gamma$ | $W_{\\min}$ | $W_{\\max}$ "
        "| $W(P_n)$ | $W(S_n)$ | min = $P_n$ | max = $S_n$ |"
    )
    md_lines.append("|---:|---:|---:|---:|---:|---:|---:|---:|---:|:---:|:---:|")
    for r in rows:
        md_lines.append(
            f"| {r['n']} | {r['n_trees']} | "
            f"{r['alpha']:g} | {r['beta']:g} | {r['gamma']:g} | "
            f"{r['w_min']:.4f} | {r['w_max']:.4f} | "
            f"{r['w_path']:.4f} | {r['w_star']:.4f} | "
            f"{r['min_is_path']} | {r['max_is_star']} |"
        )

    md_lines.append("\n## Summary across $n$\n")
    md_lines.append(
        "Aggregated over all tree orders, the fraction of parameter "
        "triples for which the observed minimizer is $P_n$ and the "
        "observed maximizer is $S_n$:"
    )
    summary_rows = []
    for (alpha, beta, gamma) in PARAMETER_TRIPLES:
        sub = df[(df["alpha"] == alpha) & (df["beta"] == beta) & (df["gamma"] == gamma)]
        min_is_path_frac = float(sub["min_is_path"].mean())
        max_is_star_frac = float(sub["max_is_star"].mean())
        summary_rows.append((alpha, beta, gamma, min_is_path_frac, max_is_star_frac))
    md_lines.append("\n| $\\alpha$ | $\\beta$ | $\\gamma$ | fraction min = $P_n$ | fraction max = $S_n$ |")
    md_lines.append("|---:|---:|---:|---:|---:|")
    for (alpha, beta, gamma, fa, fb) in summary_rows:
        md_lines.append(f"| {alpha:g} | {beta:g} | {gamma:g} | {fa:.2f} | {fb:.2f} |")

    md_lines.append(
        "\n## Interpretation\n\n"
        "A row with `fraction min = $P_n$` $= 1.00$ and `fraction max = $S_n$` $= 1.00$ "
        "across all $n$ is consistent with Conjecture D.1 in its stated "
        "sign region. A fraction strictly between 0 and 1 indicates that "
        "the conjecture is order-dependent at that parameter triple --- "
        "the extremal switches at some $n$ --- which is interesting "
        "information for the formal derivation. A fraction of 0 indicates "
        "that the path / star is the *opposite* extremal in that parameter "
        "region (e.g. for $\\alpha < 0$ the path is typically the maximizer).\n"
    )
    md_lines.append(
        "## Unicyclic and bicyclic enumeration (TODO)\n\n"
        "`networkx` does not currently expose a built-in enumerator for "
        "non-isomorphic unicyclic or bicyclic graphs. A hand-rolled "
        "enumeration via SageMath, the `nauty` `geng` tool, or a custom "
        "Python implementation is left as a follow-up. For small orders "
        "($n \\le 9$) the counts are tractable: $46$ non-isomorphic "
        "unicyclic graphs at $n = 6$, $215$ at $n = 7$, etc.\n"
    )

    out_md = os.path.join(PROJECT, "results", "wuzi_extremal_trees.md")
    with open(out_md, "w") as f:
        f.write("\n".join(md_lines))

    print()
    print(df.to_string(index=False, float_format=lambda v: f"{v:.4f}"))
    print()
    print(f"Written {out_csv}")
    print(f"Written {out_md}")
    print(f"Done in {time.time() - t0:.1f} s.")


if __name__ == "__main__":
    main()
