"""Feature-selection comparators for Paper 2.

Compares the screening pipeline's `pairwise_pruned` / `combined_pruned`
configurations (computed by scripts/11_ml_benchmark.py) against four
external feature-selection baselines on the cached descriptor matrices.

Comparators:
  - LASSO (LassoCV-tuned alpha)               - regression datasets
  - ElasticNet (ElasticNetCV-tuned)           - regression datasets
  - mRMR (top-k by min-redundancy max-relevance,
          k matched to pairwise_pruned size)  - regression and classification
  - Boruta (Boruta-Py with RF base estimator) - regression and classification
  - L1-Logistic (LogisticRegressionCV penalty='l1') - BBBP only

The cached descriptor matrices live at
`results/{dataset}/descriptors_baseline.csv` (30 baselines + 1 target
column). BBBP descriptors are generated by `scripts/17_*.py`. All
comparators use 5-fold CV under the same KFold(seed) as
script 11 so RMSE / ROC-AUC numbers are directly comparable to
`results/ml_benchmark.csv`.

Output:
  results/paper2_feature_selection_comparison.csv

Run after scripts/17_bbbp_descriptors_and_altfamily.py if you want
the BBBP row populated.
"""
from __future__ import annotations
import csv
import os
import sys
import warnings

import numpy as np
import pandas as pd
from sklearn.linear_model import LassoCV, ElasticNetCV, LogisticRegressionCV
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.model_selection import KFold, StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, roc_auc_score, accuracy_score

warnings.filterwarnings("ignore")

PROJECT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
SEED = 20260525
N_FOLDS = 5

REGRESSION_DATASETS = [
    ("esol",          "logS"),
    ("freesolv",      "dG_hyd"),
    ("lipophilicity", "logD"),
]
CLASSIFICATION_DATASETS = [
    ("bbbp", "BBB_penetration"),
]

# Number of features pairwise_pruned keeps in script 11 (read from
# ml_benchmark.csv); we use this to size the top-k for mRMR and as
# a comparator anchor for Boruta.
PAIRWISE_K = {"esol": 7, "freesolv": 8, "lipophilicity": 8, "bbbp": 6}


def _load_dataset(name):
    path = os.path.join(PROJECT, "results", name, "descriptors_baseline.csv")
    if not os.path.exists(path):
        return None, None
    df = pd.read_csv(path)
    target_col = df.columns[-1]
    baseline_cols = list(df.columns[:30])
    X = df[baseline_cols].values.astype(float)
    y = df[target_col].values.astype(float)
    return X, y


def _eval_regression(model_factory, X, y, dataset_name):
    """5-fold CV; per fold fit fresh CV-tuned model on the train set,
    record test RMSE and number of non-zero / selected features."""
    kf = KFold(n_splits=N_FOLDS, shuffle=True, random_state=SEED)
    rmses, nfeats = [], []
    for tr, te in kf.split(X):
        scaler = StandardScaler().fit(X[tr])
        Xtr = scaler.transform(X[tr])
        Xte = scaler.transform(X[te])
        model = model_factory()
        model.fit(Xtr, y[tr])
        pred = model.predict(Xte)
        rmses.append(np.sqrt(mean_squared_error(y[te], pred)))
        if hasattr(model, "coef_"):
            nfeats.append(int(np.sum(np.abs(np.asarray(model.coef_).ravel()) > 1e-10)))
        else:
            nfeats.append(int(np.sum(model.support_)) if hasattr(model, "support_") else X.shape[1])
    return (float(np.mean(rmses)), float(np.std(rmses)),
            float(np.mean(nfeats)), float(np.std(nfeats)))


def _eval_classification(model_factory, X, y, dataset_name):
    """5-fold stratified CV; ROC-AUC + non-zero coef count."""
    kf = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=SEED)
    aucs, accs, nfeats = [], [], []
    for tr, te in kf.split(X, y):
        scaler = StandardScaler().fit(X[tr])
        Xtr = scaler.transform(X[tr])
        Xte = scaler.transform(X[te])
        model = model_factory()
        model.fit(Xtr, y[tr])
        prob = model.predict_proba(Xte)[:, 1]
        pred = model.predict(Xte)
        aucs.append(roc_auc_score(y[te], prob))
        accs.append(accuracy_score(y[te], pred))
        coef = np.asarray(model.coef_).ravel()
        nfeats.append(int(np.sum(np.abs(coef) > 1e-10)))
    return (float(np.mean(aucs)), float(np.std(aucs)),
            float(np.mean(accs)), float(np.std(accs)),
            float(np.mean(nfeats)), float(np.std(nfeats)))


def _mrmr_regression(X, y, k):
    """Minimal mRMR-like top-k selector: relevance = |corr(x_j, y)|;
    redundancy = mean |corr(x_j, x_s)| with already-selected s.
    Greedy max relevance - mean redundancy. Deterministic; no
    external dependency. (Equivalent to MID/MIQ on standardized
    Pearson r since correlations are bounded.)"""
    n_feats = X.shape[1]
    Xs = (X - X.mean(0)) / (X.std(0) + 1e-12)
    ys = (y - y.mean()) / (y.std() + 1e-12)
    rel = np.array([abs(float(np.dot(Xs[:, j], ys) / len(ys))) for j in range(n_feats)])
    selected = []
    remaining = list(range(n_feats))
    j0 = int(np.argmax(rel))
    selected.append(j0); remaining.remove(j0)
    while len(selected) < k and remaining:
        scores = []
        for j in remaining:
            red = np.mean([abs(float(np.dot(Xs[:, j], Xs[:, s]) / len(ys))) for s in selected])
            scores.append(rel[j] - red)
        best = remaining[int(np.argmax(scores))]
        selected.append(best); remaining.remove(best)
    return selected


def _mrmr_classification(X, y, k):
    """Same minimal mRMR as above; y is 0/1 so the Pearson-r
    relevance is exactly the point-biserial correlation."""
    return _mrmr_regression(X, y.astype(float), k)


def _eval_subset_regression(X, y, idx):
    """Train a RidgeCV-equivalent linear regression on the selected
    subset; report 5-fold CV RMSE. We use ordinary least squares on
    the selected k features for direct comparability with the
    pairwise_pruned RandomForest entry of script 11 (both are
    fixed-feature-set CV scores)."""
    from sklearn.linear_model import LinearRegression
    kf = KFold(n_splits=N_FOLDS, shuffle=True, random_state=SEED)
    Xsub = X[:, idx]
    rmses = []
    for tr, te in kf.split(Xsub):
        scaler = StandardScaler().fit(Xsub[tr])
        Xtr = scaler.transform(Xsub[tr])
        Xte = scaler.transform(Xsub[te])
        model = LinearRegression().fit(Xtr, y[tr])
        pred = model.predict(Xte)
        rmses.append(np.sqrt(mean_squared_error(y[te], pred)))
    return float(np.mean(rmses)), float(np.std(rmses))


def _eval_subset_classification(X, y, idx):
    """Logistic regression on the selected subset; 5-fold stratified
    CV ROC-AUC + accuracy."""
    from sklearn.linear_model import LogisticRegression
    kf = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=SEED)
    Xsub = X[:, idx]
    aucs, accs = [], []
    for tr, te in kf.split(Xsub, y):
        scaler = StandardScaler().fit(Xsub[tr])
        Xtr = scaler.transform(Xsub[tr])
        Xte = scaler.transform(Xsub[te])
        model = LogisticRegression(max_iter=2000, solver="liblinear")
        model.fit(Xtr, y[tr])
        prob = model.predict_proba(Xte)[:, 1]
        pred = model.predict(Xte)
        aucs.append(roc_auc_score(y[te], prob))
        accs.append(accuracy_score(y[te], pred))
    return float(np.mean(aucs)), float(np.std(aucs)), float(np.mean(accs)), float(np.std(accs))


def _eval_boruta_regression(X, y):
    """Boruta-Py with RandomForest base estimator. Returns 5-fold
    CV RMSE on the Boruta-selected feature set + count of confirmed
    features. Boruta is fit on the full data once (its statistical
    test is internally permutation-based and is the standard
    'wrapper' baseline)."""
    from boruta import BorutaPy
    rf = RandomForestRegressor(n_estimators=200, max_depth=7,
                               random_state=SEED, n_jobs=-1)
    boruta = BorutaPy(rf, n_estimators="auto", random_state=SEED,
                      max_iter=50, verbose=0)
    boruta.fit(X, y)
    idx = list(np.where(boruta.support_)[0])
    if len(idx) == 0:
        # Fall back: weak features. Use tentative if present.
        idx = list(np.where(boruta.support_weak_)[0])
    if len(idx) == 0:
        return (float("nan"), float("nan"), 0.0, 0.0)
    rmse_mean, rmse_std = _eval_subset_regression(X, y, idx)
    return (rmse_mean, rmse_std, float(len(idx)), 0.0)


def _eval_boruta_classification(X, y):
    from boruta import BorutaPy
    rf = RandomForestClassifier(n_estimators=200, max_depth=7,
                                random_state=SEED, n_jobs=-1)
    boruta = BorutaPy(rf, n_estimators="auto", random_state=SEED,
                      max_iter=50, verbose=0)
    boruta.fit(X, y)
    idx = list(np.where(boruta.support_)[0])
    if len(idx) == 0:
        idx = list(np.where(boruta.support_weak_)[0])
    if len(idx) == 0:
        return (float("nan"), float("nan"), float("nan"), float("nan"), 0.0, 0.0)
    auc_mean, auc_std, acc_mean, acc_std = _eval_subset_classification(X, y, idx)
    return (auc_mean, auc_std, acc_mean, acc_std, float(len(idx)), 0.0)


def main():
    out_rows = []

    # === Regression datasets ===
    for ds_name, _ in REGRESSION_DATASETS:
        X, y = _load_dataset(ds_name)
        if X is None:
            print(f"  [{ds_name}] CACHED DESCRIPTORS NOT FOUND; skipping")
            continue
        n = len(y); k = PAIRWISE_K[ds_name]
        print(f"\n--- {ds_name} (n = {n}, k_pairwise = {k}) ---")

        # LASSO
        r = _eval_regression(lambda: LassoCV(cv=5, random_state=SEED,
                                             max_iter=10000, n_alphas=50),
                             X, y, ds_name)
        print(f"  LASSO        RMSE = {r[0]:.4f} +/- {r[1]:.4f}   n_feats = {r[2]:.1f} +/- {r[3]:.1f}")
        out_rows.append(_row(ds_name, "LASSO_CV", n, r))

        # ElasticNet
        r = _eval_regression(lambda: ElasticNetCV(cv=5, l1_ratio=[0.3, 0.5, 0.7, 0.9],
                                                  random_state=SEED, max_iter=10000, n_alphas=20),
                             X, y, ds_name)
        print(f"  ElasticNet   RMSE = {r[0]:.4f} +/- {r[1]:.4f}   n_feats = {r[2]:.1f} +/- {r[3]:.1f}")
        out_rows.append(_row(ds_name, "ElasticNet_CV", n, r))

        # mRMR top-k
        idx = _mrmr_regression(X, y, k)
        mrmr_rmse_mean, mrmr_rmse_std = _eval_subset_regression(X, y, idx)
        print(f"  mRMR (k={k}) RMSE = {mrmr_rmse_mean:.4f} +/- {mrmr_rmse_std:.4f}   n_feats = {k}")
        out_rows.append({
            "dataset": ds_name, "method": f"mRMR_k{k}", "task": "regression", "n": n,
            "rmse_mean": round(mrmr_rmse_mean, 4), "rmse_std": round(mrmr_rmse_std, 4),
            "roc_auc_mean": "", "roc_auc_std": "",
            "accuracy_mean": "", "accuracy_std": "",
            "n_features_mean": float(k), "n_features_std": 0.0,
        })

        # Boruta
        try:
            br = _eval_boruta_regression(X, y)
            print(f"  Boruta       RMSE = {br[0]:.4f} +/- {br[1]:.4f}   n_feats = {br[2]:.1f}")
            out_rows.append({
                "dataset": ds_name, "method": "Boruta_RF", "task": "regression", "n": n,
                "rmse_mean": round(br[0], 4), "rmse_std": round(br[1], 4),
                "roc_auc_mean": "", "roc_auc_std": "",
                "accuracy_mean": "", "accuracy_std": "",
                "n_features_mean": br[2], "n_features_std": br[3],
            })
        except Exception as e:
            print(f"  Boruta       FAILED ({e!r})")

    # === Classification datasets (BBBP) ===
    for ds_name, _ in CLASSIFICATION_DATASETS:
        X, y = _load_dataset(ds_name)
        if X is None:
            print(f"  [{ds_name}] CACHED DESCRIPTORS NOT FOUND; skipping "
                  f"(run scripts/17_bbbp_descriptors_and_altfamily.py first)")
            continue
        y = y.astype(int)
        n = len(y); k = PAIRWISE_K[ds_name]
        print(f"\n--- {ds_name} (n = {n}, k_pairwise = {k}, classes = {dict(zip(*np.unique(y, return_counts=True)))}) ---")

        # L1-Logistic (LogisticRegressionCV with l1)
        r = _eval_classification(lambda: LogisticRegressionCV(
                cv=5, penalty="l1", solver="liblinear", Cs=20,
                max_iter=2000, random_state=SEED, scoring="roc_auc"),
            X, y, ds_name)
        print(f"  L1-Logistic  AUC  = {r[0]:.4f} +/- {r[1]:.4f}   "
              f"ACC = {r[2]:.4f} +/- {r[3]:.4f}   n_feats = {r[4]:.1f} +/- {r[5]:.1f}")
        out_rows.append({
            "dataset": ds_name, "method": "L1_Logistic_CV", "task": "classification", "n": n,
            "rmse_mean": "", "rmse_std": "",
            "roc_auc_mean": round(r[0], 4), "roc_auc_std": round(r[1], 4),
            "accuracy_mean": round(r[2], 4), "accuracy_std": round(r[3], 4),
            "n_features_mean": round(r[4], 2), "n_features_std": round(r[5], 2),
        })

        # mRMR top-k
        idx = _mrmr_classification(X, y, k)
        a_m, a_s, ac_m, ac_s = _eval_subset_classification(X, y, idx)
        print(f"  mRMR (k={k}) AUC  = {a_m:.4f} +/- {a_s:.4f}   ACC = {ac_m:.4f} +/- {ac_s:.4f}   n_feats = {k}")
        out_rows.append({
            "dataset": ds_name, "method": f"mRMR_k{k}", "task": "classification", "n": n,
            "rmse_mean": "", "rmse_std": "",
            "roc_auc_mean": round(a_m, 4), "roc_auc_std": round(a_s, 4),
            "accuracy_mean": round(ac_m, 4), "accuracy_std": round(ac_s, 4),
            "n_features_mean": float(k), "n_features_std": 0.0,
        })

        # Boruta
        try:
            br = _eval_boruta_classification(X, y)
            print(f"  Boruta       AUC  = {br[0]:.4f} +/- {br[1]:.4f}   "
                  f"ACC = {br[2]:.4f} +/- {br[3]:.4f}   n_feats = {br[4]:.1f}")
            out_rows.append({
                "dataset": ds_name, "method": "Boruta_RF", "task": "classification", "n": n,
                "rmse_mean": "", "rmse_std": "",
                "roc_auc_mean": round(br[0], 4), "roc_auc_std": round(br[1], 4),
                "accuracy_mean": round(br[2], 4), "accuracy_std": round(br[3], 4),
                "n_features_mean": br[4], "n_features_std": br[5],
            })
        except Exception as e:
            print(f"  Boruta       FAILED ({e!r})")

    # Save
    out_path = os.path.join(PROJECT, "results", "paper2_feature_selection_comparison.csv")
    if out_rows:
        with open(out_path, "w", newline="") as f:
            fields = ["dataset", "method", "task", "n",
                      "rmse_mean", "rmse_std",
                      "roc_auc_mean", "roc_auc_std",
                      "accuracy_mean", "accuracy_std",
                      "n_features_mean", "n_features_std"]
            writer = csv.DictWriter(f, fieldnames=fields)
            writer.writeheader()
            for r in out_rows:
                writer.writerow(r)
        print(f"\nWrote {out_path}")


def _row(ds_name, method, n, r):
    return {
        "dataset": ds_name, "method": method, "task": "regression", "n": n,
        "rmse_mean": round(r[0], 4), "rmse_std": round(r[1], 4),
        "roc_auc_mean": "", "roc_auc_std": "",
        "accuracy_mean": "", "accuracy_std": "",
        "n_features_mean": round(r[2], 2), "n_features_std": round(r[3], 2),
    }


if __name__ == "__main__":
    main()
